language: c
sudo: required

notifications:
  email:
    recipients:
      - manodeep@gmail.com
    on_success: change
    on_failure: always

env:
  global:
    - NUMPY_VERSION=1.12
    - DOCTEST=TRUE
    - CORRFUNC_CI=TRUE

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - libgsl0-dev

matrix:
  fast_finish: true

  include:
    #### osx with clang doesn't use openmp -> so they are the slowest. Run them first
    # - os: osx
    #   compiler: gcc
    #   env: COMPILER=gcc-4.9 FAMILY=gcc V='4.9' PYTHON_VERSION=2.6 NUMPY_VERSION=1.7
    #   before_install:
    #     - brew update
    #     - brew tap homebrew/versions && brew reinstall gcc49 --without-multilib
    #     - wget https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh

    # - os: osx
    #   compiler: clang
    #   env: COMPILER=clang-omp FAMILY=clang V='3.5' PYTHON_VERSION=2.7
    #   before_install:
    #     - brew update
    #     - brew outdated xctool || brew upgrade xctool
    #     - brew tap homebrew/versions && brew install clang-omp
    #     - wget https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh
    - os: osx
      osx_image: xcode9
      compiler: clang
      env: COMPILER=clang FAMILY=clang V='Apple LLVM 7.0.0' PYTHON_VERSION=3.6 DOCTEST=FALSE
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh


    - os: osx
      osx_image: xcode8
      compiler: clang
      env: COMPILER=clang FAMILY=clang V='Apple LLVM 7.0.0' PYTHON_VERSION=3.5 DOCTEST=FALSE
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh

    - os: osx
      osx_image: xcode8
      compiler: clang
      env: COMPILER=clang FAMILY=clang V='Apple LLVM 7.0.0' PYTHON_VERSION=2.7 DOCTEST=FALSE
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh

    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: COMPILER=gcc PYTHON_VERSION=2.7
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh

    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: COMPILER=gcc PYTHON_VERSION=3.5
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: COMPILER=gcc PYTHON_VERSION=3.6
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: COMPILER=gcc PYTHON_VERSION=3.7 NUMPY_VERSION=1.16
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

install:
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda create -q --yes -n test python=$PYTHON_VERSION
  - source activate test
  - conda install -q --yes numpy=$NUMPY_VERSION || conda install -q --yes -c conda-forge numpy=$NUMPY_VERSION
  - conda install -q --yes -c conda-forge gsl
  - python -m pip install --upgrade pip
  - python -m pip install --ignore-installed certifi --upgrade
  - python -m pip install sphinx>=1.8
  - make -r CC=$COMPILER
  - make install CC=$COMPILER
  - python -m pip install -e .

script:
  - echo $CFLAGS
  - make tests CC=$COMPILER
  - make -C docs html
  - if [[ "${DOCTEST}" == "TRUE" ]]; then make -C docs doctest ; fi

branches:
  only:
    - master
