notifications:
  email: false

language: c
sudo: false

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.8','libgsl0-dev','python-numpy']
      env: COMPILER=gcc-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.9','libgsl0-dev','python-numpy']
      env: COMPILER=gcc-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-5','libgsl0-dev','python-numpy']
      env: COMPILER=gcc-5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['libgsl0-dev','python-numpy']
      env: COMPILER=clang V='3.4'

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5','libgsl0-dev','python-numpy']
      env: COMPILER=clang-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6','libgsl0-dev','python-numpy']
      env: COMPILER=clang-3.6 V=3.6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7','libgsl0-dev','python-numpy']
      env: COMPILER=clang-3.7 V=3.7

#     - os: linux
#       compiler: gcc
#       addons:
#         apt:
#           sources: ['ubuntu-toolchain-r-test']
#           packages: ['gcc-5','libgsl0-dev','python-numpy']
#       env:
#         - COMPILER=gcc-5
#       before_script:
#         - pip install --user cpp-coveralls
#       after_success:
#         - coveralls --gcov gcov-5 --gcov-options '\-lp' --exclude xi_theory/tests  --exclude xi_mocks/tests --exclude examples

    - os: osx
      compiler: clang
      env: COMPILER=clang

      before_install:
			  - brew update
				- brew install numpy && brew install gsl
# 				- brew outdated gsl || brew upgrade gsl
# 				- brew outdated numpy || brew upgrade numpy


    - os: osx
      osx_image: xcode7
      compiler: clang
      env: COMPILER=clang V='Apple LLVM 7.0.0'

      before_install:
			  - brew update && brew install numpy && brew install gsl

script:
  - make distclean && make -j4 install CC=$COMPILER && make -j4 tests CC=$COMPILER
  - cd xi_theory/python_bindings && python call_correlation_functions.py
  - cd ../../xi_mocks/python_bindings && python call_correlation_functions_mocks.py
